name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - run: pnpm run test
      - run: pnpm run lint
