name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - run: pnpm test
      - run: pnpm lint
      - run: pnpm build
